- name: Ensure Python 2 is installed
  become: true
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python)

- name: Ensure we are able to connect to VM(s)
  ping:

- name: Ensure Certbot is installed
  become: true
  apt: name=letsencrypt update_cache=yes

- name: Provision certificate with Certbot
  become: true
  command: "letsencrypt -n --keep-until-expiring --standalone certonly --agree-tos --email {{ cert_email_address }} -d {{ domain_name }}"

- name: Setup auto-renewal of certificate with Certbot
  become: true
  cron: name="Renew certificate" minute=22 hour=5 job="letsencrypt renew --agree-tos --email {{ cert_email_address }}"

