- name: Ensure Python 2 is installed
  become: true
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python)

- name: Ensure we are able to connect to VM(s)
  ping:

- name: Ensure Certbot is installed
  become: true
  apt: name=letsencrypt update_cache=yes

- name: Provision certificate with Certbot
  become: true
  command: "letsencrypt --standalone certonly --agree-tos --email {{ cert_email_address }} -d {{ domain_name }}"

- name: Setup auto-renewal of certificate with Certbot
  become: true
  command: echo TODO

